Fix error: type `std::path::Display<'_,std::path::posix::Path>` does not implement any method in scope named `to_str`
Since `Path` implements `ToCStr`, it can be passed to Command::arg()
directly.